export const goals = [{
    actions: ['actions'],
    benefits: ['gain'],
    consequences: ['what will happen'],
    criteria: ['important'],
    description: ['example description'],
    difference: ['ps to ds diff'],
    ecological: ['good for self, others, community, world'],
    evidence: ['measurable'],
    feel: ['kino'],
    goal: 'example goal',
    goalid: 0,
    hear: ['auditory'],
    purpose: ['meta'],
    obstacles: ['stops'],
    opportunitycost: ['trade off'],
    resources: ['my resources'],
    rolemodels: ['who has done this'],
    see: ['visual'],
    skills: ['know how'],
    strategies: ['vak sequence of reps'],
    when: ['timeline'],
    where: ['place'],
    who: ['people'],
    slug: 'aaaa',
    lifeareas: ['school']
}]